### ISSUE TITLE
Add screenshot to the README

### ISSUE THREAD

**Issue by jtpio** [QuantStack/jupyter-drives-browser#4]
To get a better idea of what this extension does, it could be useful to add a screenshot to the README, so it's also easier to quickly see what it looks like.

Maybe it could also be useful to explain how this extension relates to https://github.com/QuantStack/jupyter-drives.

**Comment by DenisaCG** [comment]
Great point, thanks for opening this @jtpio! I opened this PR https://github.com/QuantStack/jupyter-drives-browser/pull/7 to address it.
